Include CMake Config in CMake installation process
trixi-framework/FTObjectLibrary pull request #14
Opened 2021-06-19 00:55 UTC by schoonovernumerics

CMake config files make it possible for other projects (such as HOHQMesh) to easily find the necessary paths to includes directories and libraries. 

This PR brings in an update to the CMake build system to install a CMake configuration file so that installation of dependent applications, like HOHQMesh, does not require bespoke CMake cache variables. Instead, this allows for dependent projects to use `FIND_PACKAGE()` intrinsics in CMake to define paths for FTOL dependencies.

2021-06-19 11:43 UTC, sloede requested changes
Aside some minor comments, this looks good to me! Three more things to consider:

* It would be nice to add some tests for building FTOL using the `CMake` build system. Even though they would just be smoke tests that exercise the build system, PRs to add these tests to the GitHub Actions CI script would be welcome ;-)
* Have you thought about making the CMake minimum version something more recent to make use of more convenience features? E.g., 3.12 is already 3 years and had a lot of great features, so this would be a good start IMHO. Or, to be more inclusive (though less up-to-date), once could also require 3.10, which is included in Ubuntu 18.04 LTS.
* Have you considered making CMake the only way to build FTOL? To me, it seems error prone and it duplicates work to maintain two separate build systems. What's your take on this?

2021-06-19 11:43 UTC, sloede commented on CMakeLists.txt
>  SET(FFLAGS "-cpp" CACHE STRING "Fortran compiler flags")
While you're at it, you might want to consider adapting the default flags to what is used in the `Makefile`:
https://github.com/trixi-framework/FTObjectLibrary/blob/463514f2210534c2201461a2902945c3d6bad9e7/makeLibrary/Makefile#L6-L17

2021-06-19 11:43 UTC, sloede commented on CMakeLists.txt
> +configure_package_config_file(ftobjectlibrary-config.cmake.in
Are you keen on using the lowercase version of the CMake config file? IIRC, the "canonical" style of CMake (if there is any), is to always use camel case. Since FTObjectLibrary is also styled this way, it might make sense to name these files `FTObjectLibaryConfig.cmake.in` and `FTObjectLibraryConfig.cmake`. But this is merely a suggestion :-)

2021-06-19 15:23 UTC, schoonovernumerics commented
Thanks for your feedback. I agree with you on the CI build tests with CMake.

TBH, I had not thought about moving the minimum CMake version up. To your point, seeing what is shipped with common distro's is likely important.

I had thought about making CMake the only build system, but I recall @DavidAKopriva  having trouble using it on Mac OS. 

Building Spack packages with CMake is far easier. Since Spack grabs the required CMake version and builds from source, I'd be interested to find out if this works around that issue.

2021-06-19 19:38 UTC, schoonovernumerics commented on CMakeLists.txt
>  SET(FFLAGS "-cpp" CACHE STRING "Fortran compiler flags")
I've pushed up a commit that sets the default `FFLAGS` to the same defaults in this makefile.

2021-06-19 19:39 UTC, schoonovernumerics commented on CMakeLists.txt
> +configure_package_config_file(ftobjectlibrary-config.cmake.in
Camel case looks better and there's no reason not to make this change. Functionally this causes no issues integrating with Spack or building HOHQMesh. I've pushed up a commit that has this config file (and the template input) conforming to camel case.

2021-06-19 20:12 UTC, schoonovernumerics commented
In the last commit, I added a CI test for the Github actions to test the CMake build as well. It only runs up to `make` (not `make install`), but it seems to be working in tests on the HigherOrderMethods fork (https://github.com/HigherOrderMethods/FTObjectLibrary/actions/runs/953088076)

Consistent with @DavidAKopriva 's experience, the CMake build fails on MacOS.

2021-06-20 15:14 UTC, sloede requested changes
Thanks for the changes! I've left two more minor remarks/suggestions.

2021-06-20 15:14 UTC, sloede commented on CMakeLists.txt
>  SET(FFLAGS "-cpp" CACHE STRING "Fortran compiler flags")
:+1:

2021-06-20 15:15 UTC, sloede commented
@schoonovernumerics Also, please update your branch with the latest main. Sorry, forgot to mention that in my previous message.

2021-06-21 16:38 UTC, schoonovernumerics commented on .github/workflows/ci.yml
> +          mkdir build && cd build
I've added `build/` to the .gitignore.

2021-06-21 16:38 UTC, schoonovernumerics commented
HOM fork has been updated to be consistent with the trixi-framework branch

2021-06-22 04:17 UTC, sloede commented on .github/workflows/ci.yml
> +          make
```suggestion
      - name: Verify CMake build
        run: |
          mkdir build && cd build
          cmake ../
          make
        env:
          FC: ${{ matrix.compiler }}
```
The current build fails on Windows due to the different way how environment variables are set there (see [error log](https://github.com/trixi-framework/FTObjectLibrary/pull/14/checks?check_run_id=2877784509#step:3:12)). Let's see if this fixes the issues.

2021-06-23 03:54 UTC, sloede approved these changes

2021-06-23 04:03 UTC, merged