Readme - On Spack
trixi-framework/FTObjectLibrary pull request #16
Opened 2021-06-24 14:55 UTC by schoonovernumerics

I've added some documentation for installing FTObjectLibrary via spack. Additionally, there are notes on how to contribute new version releases for FTOL to the Spack package manager.

Ideally, you should be able to install Spack using the instructions provided.

2021-07-11 04:40 UTC, sloede requested changes
Just two minor suggestions, otherwise this LGTM!

2021-07-11 04:40 UTC, sloede commented on README.md
> +1. Fork the Spack repository on Github to your personal account or the trixi-framework organization account.
```suggestion
1. Fork the Spack repository on GitHub.
```
Forks should never go into the organization account.

2021-07-11 04:40 UTC, sloede commented on README.md
> +10. Open a Pull Request with `github.com/spack/spack` to merge your changes with the `spack/spack/develop` branch.
```suggestion
10. Open a Pull Request against `github.com/spack/spack` to merge your changes with the `spack/spack/develop` branch.
```
I think "open a pull request *against* a repo/branch" is the typical GH lingo

2022-03-19 18:36 UTC, DavidAKopriva approved these changes
OK. Sorry I didn't know about the review request.

2024-11-08 09:41 UTC, andrewwinters5000 approved these changes

2024-11-08 09:45 UTC, merged