Increase coverage
trixi-framework/FTObjectLibrary pull request #21
Opened 2023-05-26 21:50 UTC by DavidAKopriva

Add coverage for valueDictionary methods.

2023-05-29 07:26 UTC, andrewwinters5000 requested changes
LGTM! Just a small syntax suggestion.

2023-05-29 07:26 UTC, andrewwinters5000 commented on Testing/Tests/ValueClassTests.f90
> +         ALLOCATE(v)
```suggestion
            ALLOCATE(v)
```

2023-05-29 15:54 UTC, DavidAKopriva commented on Testing/Tests/ValueClassTests.f90
> +         ALLOCATE(v)
Done. Will appear in the next commit.

2023-06-26 09:32 UTC, andrewwinters5000 requested changes
Nice work @DavidAKopriva adding all the new tests! I know that this process can be very tiresome. Most of my suggestions are formatting related as everything else already looks good.

2023-06-26 09:32 UTC, andrewwinters5000 commented on Source/FTTesting/Assert.f90
> +!      and there can be a lot of errors to report.
In a loop we could then make the appropriate comparison and save the result into a temporary `LOGICAL` variable. On the fly we could then report which position fails (if any) and report the troublesome values.

2023-06-26 09:32 UTC, andrewwinters5000 commented on Source/FTTesting/Assert.f90
> +         REAL, INTENT(in)           :: expectedValue,actualValue,relTol
```suggestion
         REAL, INTENT(IN)           :: expectedValue,actualValue,relTol
```

2023-06-26 09:32 UTC, andrewwinters5000 commented on Source/FTTesting/Assert.f90
> +         DOUBLE PRECISION, INTENT(in)             :: expectedValue,actualValue,relTol
```suggestion
         DOUBLE PRECISION, INTENT(IN)             :: expectedValue,actualValue,relTol
```

2023-06-26 15:39 UTC, DavidAKopriva commented on Source/FTTesting/Assert.f90
> +!      and there can be a lot of errors to report.
The procedure called in the assert returns an array marking where the results differ, so the information is available. The only problem is that the number of those could be huge, so reporting so many positions may be impractical. Perhaps some formatting like Julia does for large arrays where only results near the ends are written and ... is used to indicate skipping over a bunch of them. Some decision as to how big an array is "too being" and needs to be truncated would have to be made.

2023-06-26 17:39 UTC, andrewwinters5000 commented on Source/FTTesting/Assert.f90
> +!      and there can be a lot of errors to report.
Ah, okay. I see what you mean

2023-06-27 04:32 UTC, andrewwinters5000 commented on Source/FTTesting/Assert.f90
> +!      and there can be a lot of errors to report.
I opened a corresponding issue #26 to keep track on this.

2023-06-27 16:36 UTC, andrewwinters5000 approved these changes
LGTM!

2023-06-27 16:37 UTC, merged